version: "{build}"

branches:
  only:
    - master

matrix:
  fast_finish: true

platform: Any CPU

configuration:
  - Debug
  - Release

test_script:
  - Tests\Examples\bin\%CONFIGURATION%\Examples.exe
