version: "{build}"

branches:
  only:
    - master

matrix:
  fast_finish: true

install:
  - NuGet restore PPrint.sln

platform: Any CPU

configuration:
  - Debug
  - Release

test_script:
  - Tests\Examples\bin\Debug\Examples.exe
  - Tests\Examples\bin\Release\Examples.exe
